project_id = "otdmqmpxukifoxjlgzmq"

[functions.assign-specialist]
verify_jwt = false

[functions.analyze-plant]
verify_jwt = false

[functions.notify-expert]
verify_jwt = false

[functions.analyze-with-cloud-vision]
verify_jwt = false

[functions.analyze-with-rougen]
verify_jwt = false

[functions.analyze-plant-diseases]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-specialist-notification]
verify_jwt = false

[functions.cdc-event-processor]
verify_jwt = false

[functions.cdc-webhook-handler]
verify_jwt = false

[functions.send-firebase-notification]
verify_jwt = false

[functions.notify-chat-message]
verify_jwt = false

[functions.delete-conversation]
verify_jwt = false

[functions.delete-consultation]
verify_jwt = false

[functions.get-conversation]
verify_jwt = false

[functions.get-conversations]
verify_jwt = false

[functions.get-user-orders]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.upload-audio]
verify_jwt = false

[functions.test-secrets]
verify_jwt = false

[functions.gpt-vision-diagnosis]
verify_jwt = false

[functions.plant-id-diagnosis]
verify_jwt = false

[functions.plantnet-identification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.unified-plant-diagnosis]
verify_jwt = false

[functions.real-plant-diagnosis]
verify_jwt = false

[functions.crop-health-analysis]
verify_jwt = false

[functions.generate-professional-pdf]
verify_jwt = true

[functions.save-diagnosis]
verify_jwt = true

# 👇 aggiungi la tua funzione EPPO qui
[functions.eppo-api]
verify_jwt = false

[auth.hooks.send_email]
enabled = true
uri = "{{PROJECT_REF}}/functions/v1/send-password-reset"

# 👇 nuova sezione per chiarezza: elenco dei secrets usati dal progetto
[secrets]
OPENAI_API_KEY = "sk-..."
PLANT_ID_API_KEY = "..."
PLANTNET_API_KEY = "..."
EPPO_AUTH_TOKEN = "9159803cacf305136f429b555feac7b6"
