
project_id = "otdmqmpxukifoxjlgzmq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true
port = 54327

[vector]
enabled = true
port = 54328

[functions.analyze-plant]
verify_jwt = false

[functions.configure-auth-settings]
verify_jwt = false

[functions.eppo-api]
verify_jwt = false

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-specialist-notification]
verify_jwt = false

[functions.update-conversation-last-message-trigger]
verify_jwt = false

