
project_id = "otdmqmpxukifoxjlgzmq"

[functions.analyze-plant]
verify_jwt = false

[functions.notify-expert]
verify_jwt = false

[functions.analyze-with-cloud-vision]
verify_jwt = false

[functions.analyze-with-rougen]
verify_jwt = false

[functions.analyze-plant-diseases]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
