
project_id = "otdmqmpxukifoxjlgzmq"

[functions.analyze-plant]
verify_jwt = false

[functions.notify-expert]
verify_jwt = false

[functions.analyze-with-cloud-vision]
verify_jwt = false

[functions.analyze-with-rougen]
verify_jwt = false

[functions.analyze-plant-diseases]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-specialist-notification]
verify_jwt = false

[functions.cdc-event-processor]
verify_jwt = false

[functions.cdc-webhook-handler]
verify_jwt = false

[functions.send-firebase-notification]
verify_jwt = false

[functions.notify-chat-message]
verify_jwt = false

[auth.hooks.send_email]
enabled = true
uri = "{{PROJECT_REF}}/functions/v1/send-registration-confirmation"
