
# This file lists all the edge functions that will be deployed with the app
project_id = "otdmqmpxukifoxjlgzmq"

[functions.analyze-plant]
verify_jwt = false

[functions.notify-expert]
verify_jwt = false

[functions.analyze-with-cloud-vision]
verify_jwt = false

[functions.analyze-with-rougen]
verify_jwt = false

[functions.analyze-plant-diseases]
verify_jwt = false
