
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useTheme } from "@/context/ThemeContext";

type PrivacyPolicyModalProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

const PrivacyPolicyModal = ({ open, onOpenChange }: PrivacyPolicyModalProps) => {
  const { t } = useTheme();
  
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle className="text-xl font-bold">{t("privacyPolicy")}</DialogTitle>
          <DialogDescription>Last updated: May 5, 2025</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] mt-4">
          <div className="space-y-4 pr-4">
            <section>
              <h2 className="text-lg font-semibold mb-2">Introduction</h2>
              <p className="text-sm text-gray-600">
                Plant Patho Pal ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Plant Patho Pal. This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Plant Patho Pal. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
              </p>
            </section>
            
            <section>
              <h2 className="text-lg font-semibold mb-2">Definitions and Key Terms</h2>
              <p className="text-sm text-gray-600">
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
              </p>
              <ul className="list-disc pl-5 mt-2 text-sm text-gray-600">
                <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li>Company: when this policy mentions "Company," "we," "us," or "our," it refers to Plant Patho Pal, that is responsible for your information under this Privacy Policy.</li>
                <li>Country: where Plant Patho Pal or the owners/founders of Plant Patho Pal are based, in this case is Italy.</li>
                <li>Customer: refers to the company, organization or person that signs up to use the Plant Patho Pal Service to manage the relationships with your consumers or service users.</li>
                <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Plant Patho Pal and use the services.</li>
                <li>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li>Personnel: refers to those individuals who are employed by Plant Patho Pal or are under contract to perform a service on behalf of one of the parties.</li>
                <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li>Service: refers to the service provided by Plant Patho Pal as described in the relative terms (if available) and on this platform.</li>
                <li>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li>Website: Plant Patho Pal's site, which can be accessed via this URL: www.plantpathopal.com</li>
                <li>You: a person or entity that is registered with Plant Patho Pal to use the Services.</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-lg font-semibold mb-2">Information We Collect</h2>
              <p className="text-sm text-gray-600">
                We collect information from you when you visit our application, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
              </p>
              <ul className="list-disc pl-5 mt-2 text-sm text-gray-600">
                <li>Name / Username</li>
                <li>Email Addresses</li>
                <li>Password</li>
                <li>Location Data</li>
                <li>Usage Data (plant diagnoses, orders, saved plant data)</li>
                <li>Device Information</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-lg font-semibold mb-2">How We Use Your Information</h2>
              <p className="text-sm text-gray-600">
                We use the information we collect in various ways, including to:
              </p>
              <ul className="list-disc pl-5 mt-2 text-sm text-gray-600">
                <li>Provide, operate, and maintain our application</li>
                <li>Improve, personalize, and expand our application</li>
                <li>Understand and analyze how you use our application</li>
                <li>Develop new products, services, features, and functionality</li>
                <li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the application, and for marketing and promotional purposes</li>
                <li>Send you emails</li>
                <li>Find and prevent fraud</li>
                <li>Provide plant disease diagnosis and treatment recommendations</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-lg font-semibold mb-2">Security of Your Personal Information</h2>
              <p className="text-sm text-gray-600">
                We implement security measures to maintain the safety of your personal information when you enter, submit, or access your personal information. We offer the use of a secure server. All plant data and diagnoses provided by the user are encrypted using industry-standard technology.
              </p>
            </section>
            
            <section>
              <h2 className="text-lg font-semibold mb-2">Contact Us</h2>
              <p className="text-sm text-gray-600">
                If you have any questions about this Privacy Policy, please contact us:
              </p>
              <ul className="list-disc pl-5 mt-2 text-sm text-gray-600">
                <li>By email: privacy@plantpathopal.com</li>
                <li>By visiting this page on our website: www.plantpathopal.com/contact</li>
                <li>By phone number: +123 456 7890</li>
              </ul>
            </section>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};

export default PrivacyPolicyModal;
